---
abstract: 'Perl core IO modules'
author:
  - 'Perl5 Porters <perl5-porters@perl.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO
no_index:
  directory:
    - t
    - inc
requires:
  File::Temp: '0.15'
  Test::More: '0'
resources:
  MailingList: http://lists.perl.org/list/perl5-porters.html
  bugtracker: https://github.com/perl/perl5/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Perl/perl5/tree/blead/dist/IO
version: '1.55'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
